import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import TheHeader from "@/components/ui/layout/TheHeader";
import {layoutConfig} from "@/configs/layoutConfig";
import Script from "next/script";
import {TgProvider} from "@/providers/tgProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
    <head>
      {/* Скрипт Telegram WebApp */}
      <Script
        src="https://telegram.org/js/telegram-web-app.js?59"
        strategy="beforeInteractive"
      />
    </head>
    <body
      className={`
        min-h-screen
        m-auto
        bg-sky-950 text-white 
        ${geistSans.variable} ${geistMono.variable} antialiased
        ${layoutConfig.flexColItemsOnly}`}>
    <TgProvider>
      <TheHeader/>
      <main className='mt-10'>{children}</main>
      <footer className='mt-10'>footer если нужен вообще</footer>
    </TgProvider>
    </body>
    </html>
  );
}
