import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TheHeader from "@/components/ui/layout/TheHeader";
import {layoutConfig} from "@/configs/layoutConfig";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
        min-h-screen
        m-auto
        bg-sky-950 text-white 
        ${geistSans.variable} ${geistMono.variable} antialiased
        ${layoutConfig.flexColItemsOnly}`}>
      <TheHeader/>
      <main className='mt-10'>{children}</main>
      <footer className='mt-10'>footer если нужен вообще</footer>
      </body>
    </html>
  );
}
